accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete,
)

app_name = 'accounts'
urlpatterns = [
    #loginpage
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),

    #logoutpage
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),

    #registerpage
    url(r'^register/$', views.register, name='register'),

    # profilepage
    url(r'^profile/$', views.ViewProfile.as_view(), name='view_profile'),

    # friendsprofilepage
    url(r'^profile/(?P<pk>\d+)/$', views.ViewProfile.as_view(), name='view_profile_with_pk'),
    #profileeditpage
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

    #change-passwordpage
    url(r'^profile/password/$', views.change_password, name='change_password'),

    #password_resetPage
    url(r'^reset-password/$', password_reset, {'template_name':
    'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done' ,
    'email_template_name':'accounts/reset_password_email.html'}, name='reset_password'),

    #password_reset_done
    url(r'^reset-password/done/$', password_reset_done, {'template_name':'accounts/reset_password_done.html'},
    name='password_reset_done'),

    #sendsemail
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':'accounts/reset_password_confirm.html',
    'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name':'accounts/reset_password_complete.html'},name='password_reset_complete'),
    # profilepage
    url(r'^profile/$', views.ViewProfile.as_view(), name='view_profile'),




	]

post/urls.py
from django.conf.urls import url, include
from .views import (
    IndexView,
    DetailView,
    RooteCreate,
    LocationCreate,
    RooteUpdate,
    RooteLikeToggle,
    RooteDelete,
    RooteDelete,
    FoodyView,
    UrbanView,
    NightLifeView,
    OutDoorsView,
    HomeView,
    TemplateView,
    PicView,
    )
app_name = 'post'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^choice/$', TemplateView.as_view(), name='choice'),

    url(r'^pic/$', PicView.as_view(), name='pic'),

     #/post/id
    url(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name='detail'),

    #adding rootes
    url(r'^roote/add/$', RooteCreate.as_view(), name='roote-add'),

	#adding Locations
    url(r'^location/add/$', LocationCreate.as_view(), name='location-add'),

    #updating rootes
    url(r'^(?P<pk>[0-9]+)/edit/$', RooteUpdate.as_view(), name='roote-update'),

    #like roote
    url(r'^(?P<pk>[0-9]+)/like/$', RooteLikeToggle.as_view(), name='like-toggle'),

    #deleting rootes
    url(r'^(?P<pk>[0-9]+)/delete/$', RooteDelete.as_view(), name='roote-delete'),

    #foody
    url(r'^foody/$', FoodyView.as_view(), name='foody'),

    #urban
    url(r'^urban/$', UrbanView.as_view(), name='urban'),

    #nightlife
    url(r'^nightlife/$', NightLifeView.as_view(), name='night'),

    #outdoors
    url(r'^outdoors/$', OutDoorsView.as_view(), name='outdoors'),

    # profilepage
     url(r'^home/$', HomeView.as_view(), name='home'),


]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from website import views



urlpatterns = [
    url(r'^$', views.index_redirect,  name='index_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/post/', include("post.api.urls", namespace='post-api')),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),


    ]







if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Houston')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    bio = models.CharField(max_length=100, default='')
    city =  models.CharField(max_length=100, default='')
    image = models.ImageField(upload_to='profile_image', blank= True)
    objects = models.Manager()
    houston = UserProfileManager()

    # this how to associate the UserProfileManager to the user profile
    def __str__(self):
        return self.user.username

def create_profile(sender ,**kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile
__all__ = [UserProfile]

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = UserProfile
        fields = (
            'image',
            'bio',
        )
# UserChangeForm deletion of the password

    def __init__(self,*args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        del self.fields['password']

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)
from django.views.generic.edit import CreateView

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash,authenticate,login
from django.shortcuts import get_object_or_404
from accounts.models import UserProfile
from django.core.urlresolvers import reverse_lazy
from post.models import Roote

__all__ = [User, UserChangeForm]



def login_view(request):
    print ( request.user.is_authenticated () )
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username,password=password)
        login(request, user)
        print(request.user.is_authenticated())


        if user.is_active:

                    login(request, user)
                    return redirect('accounts:view_profile')


        __all__ = (username,password,user)
    return render(request, "form.html", {"form":form,"title":title})


def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username= request.POST.get('username')
            password = request.POST.get('password1')
            user = authenticate(
                request,
                username=username,
                password=password,
            )
            login(request, user)

            return redirect(reverse('accounts:view_profile'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)



def logout_view(request):
    title = "Log out Success"
    logout(request)
    return redirect('accounts:login')


class ViewProfile(generic.ListView):
    model = Roote
    template_name = 'accounts/profile.html'
    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        owner = get_object_or_404(User, pk=pk) if pk else request.user  # <<<

        users = User.objects.exclude(id=request.user.id)[:]
        object_list = Roote.objects.filter(owner=owner).order_by('-timestamp')
        context = {'object_list': object_list, 'users': users,'user': owner}

        return render(request, self.template_name, context)



#this is the new edit page form
def edit_profile(request):
    if request.method =='POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form= EditProfileForm(instance=request.user)
        kwargs = {'form': form}
        return render(request,'accounts/edit_profile.html', kwargs)


def change_password(request):
    if request.method=='POST':
        form= PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:view_profile')
        else:
            return redirect('change-password')
    else:
        form= PasswordChangeForm(user=request.user)
        kwargs = {'form': form}
        return render(request,'change-password.html', kwargs)

accounts/templates/accounts/change-password.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container" style="margin-top: 60px;">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container" style="margin-top: 60px;">
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>
<br>
</div>

{% endblock %}

accounts/templates/accounts/login.html
    {% extends 'post/base.html' %}
    {% load crispy_forms_tags %}

    {% block title %}Roote Detail{% endblock %}


{% block body %}
<div class="container" style="margin-top: 60px;">
    <h1>Welcome Adventurer</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
    {% extends 'post/base.html' %}
    {% load crispy_forms_tags %}


{% block title %}Roote Detail{% endblock %}


{% block body %}
<div class="container" style="margin-top: 60px;">
		<h1>Till Next Time Adventurer</h1>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'post/base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{%block body %}
<body>
<div class="roote-container container-fluid" style="margin-top: 60px;">
  <div class='row'>
    <div class="col-md-3">
      <h1>Welcome {{user}}</h1>
          {% if user.userprofile.image %}
            <img src="{{ user.userprofile.image.url }}" width="300px" height="300px" class="img-circle" style="border-radius: 50%; border-style: solid; border-width: 2px">
          {% endif %}
    </div>
    <div class="col-md-9" style="margin-top: 20%;">
      <p>{{user}}</p>
      <p>{{user.first_name}}</p>
      <p>{{user.last_name}}</p>
      <p>{{user.email}}</p>
      <p>description: {{user.userprofile.bio}}</p>
      <p>city: {{user.userprofile.city}}</p>
    </div>
  </div>
</div>
<hr>
<div class="col" style="width: 50%; margin: 0 auto;">
<div class="roote-container container-fluid">
    <div class="row">
        <ul>
            {% for obj in object_list %}
                 <div class= "col-sm-12; width: 100px;">
                    <div class="thumbnail" style="background-color: white;">
                        <!--Roote Photo-->
                        <a href="{% url 'post:detail' obj.id %}" >
                            <img src="{{ obj.roote_photo.url }}" class="img-responsive">
                        </a>
                        <h2>{{ obj.roote_name }}</h2>
                        <p>{{ obj.user }}</p>


                            <!-- Details-->
                          <a href="{% url 'post:detail' obj.id %}" class="btn btn-default">View</a>
                          <div class="col" align="right" style="margin-top: -30px">
                             <!--delete-->
                             <form action="{% url 'post:roote-delete' obj.id %}" method="post" style="display inline;">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ obj.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                          </div>
                    </div>
                </div>
             {% endfor %}
        </ul>

    </div>
</div>

</div>

{% endblock%}

</div>
</body>

accounts/templates/accounts/reg_form.html
{%extends 'post/base.html' %}
{% load crispy_forms_tags %}
{%block title %}Add a New Account{%endblock%}


{% block body %}
<div class="container-fluid" style="margin-top: 60px;">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>Register</h1>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy}}
                       <button type="submit" class="btn btn-success">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
    {% extends 'post/base.html' %}
    {% load crispy_forms_tags %}
    {% block title %}Roote Detail{% endblock %}

{% block body %}
<div class="container" style="margin-top: 60px;">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
    {% extends 'post/base.html' %}
    {% load crispy_forms_tags %}
    {% block title %}Roote Detail{% endblock %}

{% block body %}
<div class="container-fluid" style="margin-top: 60px;">
        <div class="col-sm-6 col-sm-offset-4">
			<h1>Password Reset Complete</h1>
              <p>
                Its Complete
              </p>
              <a href="{%url 'accounts:login'%}">Login</a>
		</div>

</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
    {% extends 'post/base.html' %}
    {% load crispy_forms_tags %}
    {% block title %}Roote Detail{% endblock %}

{% block body %}
<div class="container" style="margin-top: 60px;">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
    {% extends 'post/base.html' %}
    {% load crispy_forms_tags %}
    {% block title %}Roote Detail{% endblock %}

{% block body %}
<div class="row">
        <div class="col-sm-6 col-sm-offset-4" style="margin-top: 60px;">
			<h1>Password Reset</h1>
      <p>
        We have emailed you instructions for setting your password, if an accounts
        exists with the email you entered. You should receive them shortly.

        if you dont receive an email, please make sre you've entered the address
        you registered with, and check your spam folder.
      </p>
		</div>

</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off%}
{%blocktrans%}You're receiving this email because you requested a password reset-password
for your user account at {{site_name}}.{%endblocktrans%}
{% trans "Please go to the following page and choose a new password: %"}
{%block reset_link %}
{{protocol}}://{{domain}}{%url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{%endblock%}
{%trans "Your username, incase you've  forgotten:" %} {{user.get_username}}
{%trans "Thank you for using our site!"%

{%blocktrans%}The {{site_name}} team{%endblocktrans%}

{%endautoescape%}