accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete,
)

app_name = 'accounts'
urlpatterns = [
    #loginpage
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),

    #logoutpage
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),

    #registerpage
    url(r'^register/$', views.register, name='register'),

    # profilepage
    url(r'^profile/$', views.ViewProfile.as_view(), name='view_profile'),

    # friendsprofilepage
    url(r'^profile/(?P<pk>\d+)/$', views.ViewProfile.as_view(), name='view_profile_with_pk'),
    #profileeditpage
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

    #change-passwordpage
    url(r'^profile/password/$', views.change_password, name='change_password'),

    #password_resetPage
    url(r'^reset-password/$', password_reset, {'template_name':
    'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done' ,
    'email_template_name':'accounts/reset_password_email.html'}, name='reset_password'),

    #password_reset_done
    url(r'^reset-password/done/$', password_reset_done, {'template_name':'accounts/reset_password_done.html'},
    name='password_reset_done'),

    #sendsemail
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':'accounts/reset_password_confirm.html',
    'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name':'accounts/reset_password_complete.html'},name='password_reset_complete'),
    # profilepage
    url(r'^profile/$', views.ViewProfile.as_view(), name='view_profile'),




	]

post/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    RooteListAPIView,
    RooteCreateAPIView,
    RooteDetailAPIView,
    RooteUpdateAPIView,
    RooteDeleteAPIView,
    RooteLikeAPIToggle,
    LocationListAPIView,
)


urlpatterns = [
    url(r'^$', RooteListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', RooteDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', RooteUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', RooteDeleteAPIView.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/like/$', RooteLikeAPIToggle.as_view(), name='like-api-toggle'),
    url(r'create/$', RooteCreateAPIView.as_view(), name='create'),
    url(r'^location/$', LocationListAPIView.as_view(), name='location-api-list'),
    ]

post/urls.py
from django.conf.urls import url, include
from .views import (
    IndexView,
    DetailView,
    RooteCreate,
    LocationCreate,
    RooteUpdate,
    RooteLikeToggle,
    RooteDelete,
    RooteDelete,
    FoodyView,
    UrbanView,
    NightLifeView,
    OutDoorsView,
    HomeView,
    TemplateView,
    PicView,
    )
app_name = 'post'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^choice/$', TemplateView.as_view(), name='choice'),

    url(r'^pic/$', PicView.as_view(), name='pic'),

     #/post/id
    url(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name='detail'),

    #adding rootes
    url(r'^roote/add/$', RooteCreate.as_view(), name='roote-add'),

	#adding Locations
    url(r'^location/add/$', LocationCreate.as_view(), name='location-add'),

    #updating rootes
    url(r'^(?P<pk>[0-9]+)/edit/$', RooteUpdate.as_view(), name='roote-update'),

    #like roote
    url(r'^(?P<pk>[0-9]+)/like/$', RooteLikeToggle.as_view(), name='like-toggle'),

    #deleting rootes
    url(r'^(?P<pk>[0-9]+)/delete/$', RooteDelete.as_view(), name='roote-delete'),

    #foody
    url(r'^foody/$', FoodyView.as_view(), name='foody'),

    #urban
    url(r'^urban/$', UrbanView.as_view(), name='urban'),

    #nightlife
    url(r'^nightlife/$', NightLifeView.as_view(), name='night'),

    #outdoors
    url(r'^outdoors/$', OutDoorsView.as_view(), name='outdoors'),

    # profilepage
     url(r'^home/$', HomeView.as_view(), name='home'),


]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from website import views



urlpatterns = [
    url(r'^$', views.index_redirect,  name='index_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/post/', include("post.api.urls", namespace='post-api')),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),


    ]







if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import  settings
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.contrib.contenttypes.models import ContentType


__all__=[User,settings]
# Create your models here.

User = settings.AUTH_USER_MODEL

class Category(models.Model):
    OUTDOORS = 'OUTDOORS'
    NIGHTLIFE = 'NIGHTLIFE'
    URBANEXPLORE = 'URBANEXPLORE'
    FOODY = 'FOODY'

    YOUR_CHOICES = (
        (OUTDOORS,'OUTDOORS'),
		(NIGHTLIFE,'NIGHTLIFE'),
		(URBANEXPLORE,'URBANEXPLORE'),
		(FOODY ,'FOODY')
    )
    categories = models.CharField(max_length=100, choices=YOUR_CHOICES, default='null')
    def __str__(self):
        return self.categories


class RooteManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance
        qs = super(RooteManager, self).filter(content_type=content_type , object_id = obj_id )
        return qs

class Roote(models.Model):
    likes         = models.ManyToManyField(settings.AUTH_USER_MODEL, blank =True, related_name = 'roote_likes')
    roote_name    = models.CharField(max_length=250)
    roote_photo   = models.ImageField(upload_to='roote_image')
    category      = models.ManyToManyField(Category)
    slug          = models.SlugField(null=True, blank=True)
    timestamp     = models.DateTimeField(auto_now_add=True, null=True)
    updated       = models.DateTimeField(auto_now=True, null=True)
    owner         = models.ForeignKey(User)
    objects       = RooteManager()

    def get_absolute_url(self):
    	return reverse('post:detail', kwargs={'pk': self.pk})

    def __str__(self):
    	return self.roote_name

    @property
    def title(self):
    	return self.roote_name

    def get_like_url(self):
        return reverse("post:like-toggle", kwargs={"pk": self.pk})

    def get_api_like_url(self):
        return reverse("post-api:like-api-toggle", kwargs={"pk": self.pk})

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def pre_save_roote_receiver(sender, instance, *args, **kwargs):
    print ('saving...')
    if not instance.slug:
        instance.slug = instance.slug = unique_slug_generator(instance)




pre_save.connect(pre_save_roote_receiver, sender=Roote)




class Location(models.Model):
    roote = models.ForeignKey(Roote, on_delete=models.CASCADE, null=True)
    coordinate = models.CharField(max_length=1000)
    place_name = models.CharField(max_length=250)
    city_data       = models.TextField(null=True, blank=True)
    latitude        = models.FloatField(null=True, blank=True)
    longitude       = models.FloatField(null=True, blank=True)
    session_key     = models.CharField(max_length=60, null=True, blank=True)
    ip_address      = models.GenericIPAddressField(null=True, blank=True)
    def __str__(self):
        return  self.place_name


    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'pk': self.pk})

post/api/views.py
from django.shortcuts import get_object_or_404
from django.db.models import Q
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions

from rest_framework.generics import (
     CreateAPIView,
     ListAPIView,
     RetrieveAPIView,
     DestroyAPIView,
     UpdateAPIView,
     )

from .permissions import isOwnerOrReadOnly


from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
    )

from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,

    )
from post.models import Roote, Location
from .serializers import (
        RooteListSerializer,
        RooteDetailSerializer,
        RooteCreateUpdateSerializer,
        LocationSerializer,
        )



class RooteLikeAPIToggle(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, pk=None, format=None):
        obj = get_object_or_404(Roote, pk=pk)
        url_ = obj.get_absolute_url()
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated():
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
            updated = True
        data = {
            "updated": updated,
            "liked": liked
        }
        return Response(data)



class RooteCreateAPIView(CreateAPIView):
    queryset = Roote.objects.all()
    serializer_class = RooteCreateUpdateSerializer

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
        permissions_classes = [IsAuthenticated]



class RooteListAPIView(ListAPIView):
    serializer_class = RooteListSerializer
    #Filtering through the ?search=&ordering
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['roote_name']
    #Filtering through the ?q=
    def get_queryset(self, *args, **kwargs):
        queryset_list = Roote.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                    Q(roote_name__icontains=query)
                    ).distinct()
        return queryset_list


class RooteDetailAPIView(RetrieveAPIView):
    queryset = Roote.objects.all()
    serializer_class = RooteDetailSerializer

class RooteUpdateAPIView(UpdateAPIView):
    queryset = Roote.objects.all()
    serializer_class = RooteCreateUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,isOwnerOrReadOnly,IsAdminUser]
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class RooteDeleteAPIView(DestroyAPIView):
    queryset = Roote.objects.all()
    serializer_class = RooteDetailSerializer




class LocationListAPIView(ListAPIView):
    serializer_class = LocationSerializer
    def get_queryset(self, *args, **kwargs):
        queryset_list = Location.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                    Q(place_name__icontains=query)
                    ).distinct()
        return queryset_list

post/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View, RedirectView, TemplateView
from .models import Roote, Location, Category
from analytics.models import UserSession
from django.contrib.auth.models import User
from .forms import LocationCreate
__all__=[Category,User,Location]
from rest_framework.response import Response
from analytics.signals import user_logged_in
from analytics.utils import get_client_city_data, get_client_ip
from django.db.models import Count


class HomeView(generic.ListView):
    model = Roote

    template_name = 'post/home.html'
    def get_queryset(self):
        return Roote.objects.filter(owner =self.request.user)


class IndexView(generic.ListView):
	template_name = 'post/index.html'
	context_object_name = 'all_post'

	def get_queryset(self):
		return Roote.objects.all().order_by('-timestamp')

class TemplateView(TemplateView):
    template_name = 'post/choice.html'


class PicView(TemplateView):
    template_name = 'post/pic.html'


class DetailView(generic.DetailView):
    model = Roote
    template_name = 'post/detail.html'

    def get_form_kwargs(self):
    	kwargs = super(LocationCreate, self).get_form_kwargs()
    	kwargs['user'] = self.request.user
    	return kwargs
    def get_object(self, *args, **kwargs):
         pk  =self.kwargs.get('pk')
         obj = get_object_or_404(Roote, pk=pk)
         return obj
    def get_context_data( self, *args, **kwargs ):
        context =super(DetailView, self).get_context_data(*args, **kwargs)

        query = self.request.GET.get("q")
        if query:
        	qs = Roote.objects.search(query)
        return context




def post_detail(request, pk=None):
    instance = get_object_or_404(Post, pk=pk)
    if instance.updated > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    initial_data = {
            "content_type": instance.get_content_type,
            "object_id": instance.id
    }

    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
    }
    return render(request, "posts/post_detail.html", context)



class RooteLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get("pk")
        print(pk)
        obj = get_object_or_404(Roote, pk=pk)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated():
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_



class RooteCreate(CreateView):
    model = Roote
    fields = ['roote_name', 'category', 'roote_photo']


    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner =self.request.user
        return super(RooteCreate, self).form_valid(form)




class LocationCreate(CreateView):
        model = Location
        #fields = ['roote','coordinate', 'place_name']
        success_url = reverse_lazy('post:index')
        form_class = LocationCreate

        def form_valid(self, form):
            if form.is_valid():
                roote = Roote.objects.filter(owner =self.request.user)
                instance = form.save(commit=False)
                instance.user = self.request.user
                instance.ip_address = get_client_ip(self.request)
                instance.city_data = get_client_city_data(instance.ip_address)
                if instance.city_data:
                    try:
                        instance.latitude= instance.city_data['latitude']
                    except:
                        instance.longitude = None
                    try:
                        instance.longitude= instance.city_data['longitude']
                    except:
                        instance.longitude = None
                instance.session_key = self.request.session.session_key
                user_logged_in.send(self.request.user, request=self.request)
            return super(LocationCreate, self).form_valid(form)

        def get_form_kwargs(self):
        	kwargs = super(LocationCreate, self).get_form_kwargs()
        	kwargs['user'] = self.request.user
        	return kwargs

class RooteUpdate(UpdateView):
    model = Roote
    fields = ['roote_name', 'category', 'roote_photo']



class RooteDelete(DeleteView):
    model = Roote
    success_url = reverse_lazy('post:index')

class FoodyView(generic.ListView):
    model = Roote
    template_name = 'post/foody.html'
    context_object_name = 'all_post'

    def get_queryset(self):
        return Roote.objects.filter(category__categories__startswith='FOODY').annotate(num_likes=Count('likes')).order_by('-num_likes')
class UrbanView(generic.ListView):
    model = Roote
    template_name = 'post/urban.html'
    context_object_name = 'all_post'

    def get_queryset(self):
        return Roote.objects.filter(category__categories__startswith='URBANEXPLORE').annotate(num_likes=Count('likes')).order_by('-num_likes')

class NightLifeView(generic.ListView):
    model = Roote
    template_name = 'post/nightlife.html'
    context_object_name = 'all_post'

    def get_queryset(self):
        return Roote.objects.filter(category__categories__startswith='NIGHTLIFE').annotate(num_likes=Count('likes')).order_by('-num_likes')

class OutDoorsView(generic.ListView):
    model = Roote
    template_name = 'post/outdoors.html'
    context_object_name = 'all_post'

    def get_queryset(self):
        return Roote.objects.filter(category__categories__startswith='OUTDOORS').order_by('-timestamp').annotate(num_likes=Count('likes')).order_by('-num_likes')

post/templates/post/base.html
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Roote{% endblock %}</title>
    {% load staticfiles %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'post/style.css' %}" /> -->
    <link href="https://fonts.googleapis.com/css?family=Lily+Script+One" rel="stylesheet" type='text/css' >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
<nav class="navbar navbar-inverse" style="position: fixed; top: 0; width: 100%; z-index:50;">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'post:index' %}">Roote</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
          {%if user.is_authenticated %}
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'post:index' %}">
                        <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;
                        Posts
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'accounts:view_profile' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                      Profile
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action=".">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{request.GET.q}}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
               <li class="">
                    <a href="{% url 'post:choice' %}">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp;
                        Create
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'accounts:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'accounts:edit_profile' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
                      Edit Profile
                    </a>
                </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
              <li class="">
                  <a href="{% url 'accounts:reset_password' %}">
                      <span class="glyphicon glyphicon-hdd" aria-hidden="true"></span>&nbsp;
                    Reset Password
                  </a>
              </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'post:index' %}">
                        <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;
                        Posts
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'accounts:register' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                        Create User
                    </a>
                </li>
              </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'accounts:login' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                        Log in
                    </a>
                </li>
              </ul>
            {% endif %}
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
{% block script %}
{% endblock script%}
</body>


</html>

post/templates/post/choice.html
{% extends 'post/base.html' %}
{% block body %}
<div class="container-fluid" style="margin-top: 47px;">
	<div class="row">
		<div class="col-md-12">
			</div>
				<div class="col-sm-6 col-sm-offset-3">
					<div class="roote-container container-fluid">
						<div class="row">
							<div id="mycarousel" class="carousel slide" data-ride="carousel">
								<div class="carousel-inner">
									<div class="item active">
									<a href="{% url 'post:location-add' %}">
										<img src="\static\post\images\location.jpg"  class="img-rounded  img-responsive">
										   <div class="carousel-caption">
											<h1>Location</h1>
										   </div>
									</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
        				<div class="col-sm-6 col-sm-offset-3">
        					<div class="roote-container container-fluid">
        						<div class="row">
        							<div id="mycarousel" class="carousel slide" data-ride="carousel">
        								<div class="carousel-inner">
        									<div class="item active">
        									<a href="{% url 'post:roote-add' %}">
        										<img src="\static\post\images\roote.jpg" alt="foody"  class="img-rounded  img-responsive">
        										   <div class="carousel-caption">
        											<h1>Roote</h1>
        										   </div>
        									</a>
        									</div>
        								</div>
        							</div>
        						</div>
        					</div>
        				</div>

  </div>
</div>
{% endblock %}

post/templates/post/foody.html
<html lang="en">
<head>
{% extends 'post/base.html' %}
</head>

<body>
{% block body %}

<div class="col-sm-6 col-sm-offset-3" style="margin-top: 50px;">
    <div class="roote-container container-fluid">
		<h1>Foody Rootes</h1>
        <div class="row">
                {% for post in all_post %}
                    <div class= "col-sm-12; width: 100px;">
                        <div class="thumbnail">

                            <!--Roote Photo-->
                            <a href="{% url 'post:detail' post.id %}" >
                                <img src="{{ post.roote_photo.url }}" class="img-responsive">
                            </a>

                            <div class="caption">
                                <h2>{{ post.roote_name }}</h2>
                                <p>{{ post.user }}</p>

                                <!-- Details-->
                                <a href="{% url 'post:detail' post.id %}"class="btn btn-default">View</a>

                                 <!--delete-->
                                 <div class="col" align="right" style="margin-top: -30px">
                                 <form action="{% url 'post:roote-delete' post.id %}" method="post" style="display inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="post_id" value="{{ post.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                              </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </div>
    </div>
</div>

{% endblock %}
</body>
</html>
s

post/templates/post/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

post/templates/post/index.html
<!-- Loads the path to your static files -->
<!DOCTYPE html>
{% extends 'post/base.html' %}
{% block rootes_active %}active{% endblock %}

<head>
    {% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12" style="margin-top: 30px;">
			<div class="jumbotron">
				<h2>
					Welcome Aventurer!
				</h2>
				<p>
				Roote the World!
				</p>
			</div>
				<div class="col-sm-6 col-sm-offset-3">
					<div class="roote-container container-fluid">
						<div class="row">
							<div id="mycarousel" class="carousel slide" data-ride="carousel">
								<div class="carousel-inner">
									<div class="item active">
									<a href="{% url 'post:foody' %}">
										<img src="\static\post\images\food.jpg" alt="foody"  class="img-rounded  img-responsive">
										   <div class="carousel-caption">
											<h1>Foody</h1>
										   </div>
									</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-sm-offset-3">
					<div class="roote-container container-fluid">
						<div class="row">
							<div id="mycarousel" class="carousel slide" data-ride="carousel">
								<div class="carousel-inner">
									<div class="item active">
									<a href="{% url 'post:urban' %}">
										<img src="\static\post\images\midtown.jpg" alt="urban"  class="img-rounded  img-responsive">
										   <div class="carousel-caption">
											<h1>Urban</h1>
										   </div>
									</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-sm-offset-3">
					<div class="roote-container container-fluid">
						<div class="row">
							<div id="mycarousel" class="carousel slide" data-ride="carousel">
								<div class="carousel-inner">
									<div class="item active">
									<a href="{% url 'post:night' %}">
										<img src="\static\post\images\cool.jpg" alt="nightlife"  class="img-rounded  img-responsive">
										   <div class="carousel-caption">
											<h1>Nightlife</h1>
										   </div>
									</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-sm-offset-3">
					<div class="roote-container container-fluid">
						<div class="row">
							<div id="mycarousel" class="carousel slide" data-ride="carousel">
								<div class="carousel-inner">
									<div class="item active">
									<a href="{% url 'post:outdoors' %}">
										<img src="\static\post\images\profile.jpg" alt="outdoors"  class="img-rounded  img-responsive">
										   <div class="carousel-caption">
											<h1>Outdoors</h1>
										   </div>
									</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

		</div>
    </div>
</div>

   {% endblock %}
</head>
<body>
</body>
</html>